apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-roadie-plugins-monorepo
  title: Create Roadie Plugins Monorepo
  description: Creates a Roadie plugins monorepo with example TypeScript code and example plugin with sample commands to develop, build and deploy Roadie plugins.

spec:
  owner: info@roadie.io
  type: service
  parameters:
    - title: Provide some simple information
      required:
        - plugin_name
      properties:
        plugin_name:
          title: Plugin name
          type: string
          description: Unique name of the first plugin in the repository.

    - title: Choose a Source Control Management tool to store your Roadie Plugins Monorepo in.
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
  steps:
    - id: template
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./skeleton
        values:
          repo_name: ${{ (parameters.repoUrl | parseRepoUrl)["repo"] }}
          repo_owner: ${{ (parameters.repoUrl | parseRepoUrl)["owner"] }}
          tenant: ${{ parameters.repository }}
          plugin_name: ${{ parameters.plugin_name }}

    - id: fs:rename
      name: Fill in names and descriptions
      action: fs:rename
      input:
        files:
          - from: ./plugins/my-plugin
            to: ./plugins/${{ parameters.plugin_name }}

    - id: publish
      name: Publish
      action: publish:github
      input:
        allowedHosts: ['github.com']
        description: 'This is ${{ parameters.plugin_name }}'
        repoUrl: ${{ parameters.repoUrl }}
        defaultBranch: main


  output:
    links:
      - title: Repository
        icon: github
        url: ${{ steps['publish'].output.remoteUrl }}
      - title: Roadie CLI documentation
        icon: help
        url: https://www.npmjs.com/package/@roadiehq/roadie-cli
