apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: client-notifications
  title: Send Client Notifications
  description: Send a notification to all client external slack channels

spec:
  owner: user:ian.link
  type: none
  parameters:
    - title: Channel
      properties:
        sendToAllClients:
          title: Send to All Clients
          description: Send this message to the all Client channels.
          type: boolean
          default: false

      if:
        properties:
          sendToAllClients:
            const: false
      then:
        properties:
          channel:
            type: string
            ui:field: SelectFieldFromApi
            ui:options:
              path: "catalog/entities"
              params:
                filter: 'kind=resource,spec.type=tenant,metadata.labels.slack-channel-id'
              labelSelector: 'metadata.name'
              valueSelector: 'metadata.labels["slack-channel-id"]'

    - title: Message
      required:
        - message
      properties:
        message:
          title: Message
          description: I support markdown!
          type: string
          ui:widget: textarea
          ui:options:
            rows: 30

  steps:
    - id: 'get-channel-ids'
      name: 'Get Channel IDs'
      action: 'http:backstage:request'
      input:
        method: 'GET'
        path: 'catalog/entities'
        params:
          filter: 'kind=resource,spec.type=tenant,metadata.labels.slack-channel-id'
          fields: 'metadata.name,metadata.labels.slack-channel-id'

    - id: 'send-notification-all-clients'
      name: 'Send Notification to All Clients'
      if: ${{ parameters.sendToAllClients }}
      each: "${{ steps['get-channel-ids'].output.body }}"
      action: 'http:backstage:request'
      input:
        method: 'POST'
        path: 'proxy/slack-roadie-announcements/chat.postMessage'
        headers:
          content-type: 'application/json'
        body:
          channel: ${{ each.value.metadata.labels["slack-channel-id"] }}
          blocks:
            - type: section
              text:
                type: mrkdwn
                text: ${{ parameters.message }}

    - id: 'send-notification-single-client'
      name: 'Send Notification to Single Client'
      if: ${{ parameters.sendToAllClients == false }}
      action: 'http:backstage:request'
      input:
        method: 'POST'
        path: 'proxy/slack-roadie-announcements/chat.postMessage'
        headers:
          content-type: 'application/json'
        body:
          channel: ${{ parameters.channel }}
          blocks:
            - type: section
              text:
                type: mrkdwn
                text: ${{ parameters.message }}