apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-roadie-agent-scaffolder-action-mono-repo
  title: Create Roadie Agent Scaffolder Action Repository
  description: Create a Roadie Agent service repository to execute a scaffolder action from your infrastructure. You can run this once to create the repo, and then add multiple scaffolder actions in the created repo.

spec:
  owner: info@roadie.io
  type: service
  parameters:
    - title: Provide some simple information
      required:
        - agent_name
      properties:
        agent_name:
          title: Name
          type: string
          description: Unique name of the Roadie Agent Scaffolder Action repository.

    - title: Choose a Source Control Management tool to store your Roadie Agent Service in.
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
  steps:
    - id: template
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./skeleton
        values:
          repo_name: ${{ (parameters.repoUrl | parseRepoUrl)["repo"] }}
          repo_owner: ${{ (parameters.repoUrl | parseRepoUrl)["owner"] }}
          tenant: ${{ roadie.tenantName }}
          agent_name: ${{ parameters.agent_name }}

    - id: publish
      name: Publish
      action: publish:github
      input:
        allowedHosts: ['github.com']
        description: 'This is ${{ parameters.agent_name }}'
        repoUrl: ${{ parameters.repoUrl }}
        defaultBranch: main

  output:
    remoteUrl: ${{ steps.publish.output.remoteUrl }}
