apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-readme-in-repo
  title: Create a README
  description: Create a new PR with a basic README file.
spec:
  owner: group:roadiehq/engineering
  type: file

  parameters:
    - title: Basic info
      required:
        - repoName
        - name
      properties:
        repoHost:
          type: string
          default: github.com
          ui:widget: hidden
        repoOrg:
          type: string
          default: roadiehq # Change this to match the name of your GitHub org
          ui:widget: hidden
        repoName:
          title: Repository name
          type: string
        name:
          title: Human readable service name
          type: string

  steps:
    - id: fetchTemplate
      action: fetch:template
      input:
        url: ./skeleton
        templateFileExtension: .njk
        values:
          name: ${{ parameters.name }}

    - id: createPullRequest
      name: create-pull-request
      action: publish:github:pull-request
      input:
        repoUrl: ${{ parameters.repoHost }}?owner=${{ parameters.repoOrg }}&repo=${{ parameters.repoName }}
        branchName: add-readme-${{ '' | now }}
        title: Add a README file
        description: |
          This PR adds a basic README file to this repository.

          It was created via a [scaffolder template on Roadie](https://example.com).

  output:
    links:
      - title: View the pull request on GitHub
        icon: github
        url: ${{ steps['createPullRequest'].output.remoteUrl }}
      - title: Learn about writing READMEs
        icon: help
        url: https://example.com
