---
name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  deploy-dev:
    strategy:
      matrix:
        node-version: [14.x]

    env:
      AWS_PROFILE: default

    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: Fooji/create-aws-profile-action@v1
        with:
          profile: default
          key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: eu-west-1

      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: yarn install
      - run: yarn deploy --stage prod